refs: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

run-as: uchida

#env:

phases:
  build:
    commands:
      - echo Build started on 'date'
      - echo start installing packages
      - sudo apt-get install libsndfile1
      - pip install pytorch numpy librosa
  post_build:
    commands:
      - echo Build completed on 'date'
      - pwd
      - ls -al
artifacts:
  files:
    - '**/*'