version: 0.2


#env:

phases:
  build:
    commands:
      - echo "Build started"
      - echo "start installing packages"
      - mkdir python
      - cd python
      - pip install -t ./ torch numpy librosa
      - cd ../
      - apt-get update
      - apt-get -y upgrade
      - apt-get install -y libsndfile1 zip
      - zip -r audio.zip python/
  post_build:
    commands:
      - pwd
      - ls -al
artifacts:
  files:
    - '**/*'
