version: 0.2


#env:

phases:
  build:
    commands:
      - echo "Build started"
      - echo "start installing packages"
      - pip install torch numpy librosa
      - apt-get install -y libsndfile1
  post_build:
    commands:
      - pwd
      - ls -al
artifacts:
  files:
    - '**/*'
