version: 0.2


#env:

phases:
  build:
    commands:
      - echo "Build started"
      - echo "start installing packages"
        #      - cd /root
        #      - python3 -m pip install torch numpy librosa
      - pip install torch numpy librosa
      - apt-get update
      - apt-get -y upgrade
      - apt-get install -y libsndfile1
  post_build:
    commands:
      - pwd
      - ls -al
artifacts:
  files:
    - '**/*'
